---
- name: hospedate staging bucket sync
  hosts: semaphore_server
  gather_facts: yes
  vars:
    hospedate_group_security: hospedate
  roles:
    - role: hospedate-jobs-bucket
      hospedate_mode: sync                         #backup, copyfromprod, restore, cleandb
      hospedate_user: semaphore-user
      hospedate_project: hospedate                       # client
      hospedate_environment: staging             #staging, production
      hospedate_bucket_origin: s3://hospedate-prod-app/
      hospedate_bucket_target: s3://hospedate-staging-app/
      hospedate_logdir: /var/log/semaphore

