---

- name: Restart Odoo
  service:
    name: "{{ gazellaerp_service }}"
    state: restarted
  when: gazellaerp_init == True

- name: Reload Systemd
  systemd:
    daemon-reload: yes
  when: ansible_service_mgr == 'systemd'
