---


- name: "Install PYRNV for {{ gazellaerp_user }} "
  block:

    - name: PYENV - Remove pyenv directory environment
      become_user: "{{ gazellaerp_user }}"
      ansible.builtin.shell:
        cmd: "rm -rf /home/{{ gazellaerp_user }}/.pyenv"
        chdir: "/home/{{ gazellaerp_user }}"

    - name: PYENV - Install PYENV on python multiversion
      become_user: "{{ gazellaerp_user }}"
      ansible.builtin.shell:
        cmd: "curl https://pyenv.run | bash"
        chdir: "/home/{{ gazellaerp_user }}"

    - name: PYENV - Insert block of text into a bashrc configuration file
      become_user: "{{ gazellaerp_user }}"
      blockinfile:
        path: /home/{{ gazellaerp_user }}/.bashrc
        block: |
          # pyenv
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv virtualenv-init -)"
        marker: "# START ANSIBLE MANAGED BLOCK"
        state: present
        insertbefore: EOF

    - name: "PYENV - Install Python {{ gazellaerp_python }} "
      become_user: "{{ gazellaerp_user }}"
      ansible.builtin.shell: /home/{{ gazellaerp_user }}/.pyenv/bin/pyenv install -v {{ gazellaerp_python }}
      register: log_install
      args:
        executable: /bin/bash
      changed_when: true

    - name: "PYENV - DEBUG Install Python {{ gazellaerp_python }}  log"
      become_user: "{{ gazellaerp_user }}"
      ansible.builtin.debug:
        var: log_install.stdout

    - name: "PYENV - Install global version Python {{ gazellaerp_python }} "
      become_user: "{{ gazellaerp_user }}"
      ansible.builtin.shell: /home/{{ gazellaerp_user }}/.pyenv/bin/pyenv global {{ gazellaerp_python }}
      args:
        executable: /bin/bash

    - name: "PYENV - update pip3 version 20.0.2"
      become_user: "{{ gazellaerp_user }}"
      ansible.builtin.shell: "/home/{{ gazellaerp_user }}/.pyenv/shims/pip3 install pip==20.0.2 --upgrade"
      args:
        chdir: "/home/{{ gazellaerp_user }}"

    - name: "PYENV - Remove link to python {{ gazellaerp_version_main }}"
      become: yes
      ansible.builtin.shell: "rm -rf /usr/bin/python{{ gazellaerp_python_main }}"

    - name: "PYENV - Create link to python {{ gazellaerp_version_main }}"
      become: yes
      ansible.builtin.shell: "ln -s /home/{{ gazellaerp_user }}/.pyenv/versions/{{ gazellaerp_python }}/bin/python{{ gazellaerp_python_main }} /usr/bin/python{{ gazellaerp_python_main }}"
