---

- name: "Get timestamp from the system"
  shell: "date +%Y%m%d-%H%M"
  register: tstamp

- name: "Set variables"
  set_fact:
    my_date: "{{ tstamp.stdout[0:8]}}"
    my_time: "{{ tstamp.stdout[8:]}}"

- name: BUCKET - Create log directory for semaphore log
  become: yes
  ansible.builtin.file:
    path: "{{ hospedate_logdir }}"
    state: directory
    owner: "{{ hospedate_user }}"
    group: "{{ hospedate_group_security }}"
    mode: '0755'  
    force: no

- name: "BUCKET - Bucket history log on server controller"
  become: yes
  ansible.builtin.shell: echo " {{ my_date }}{{ my_time }} - {{ hospedate_environment }} - BUCKET INIT SYNC  from {{ hospedate_bucket_origin }}  to {{ hospedate_bucket_target }} " >> {{ hospedate_logdir }}/bucket-sync.log

- name: "BUCKET - Sync Bucket from {{ hospedate_bucket_origin }} to {{ hospedate_bucket_target }}"
  become: yes
  ansible.builtin.shell: "/usr/local/bin/aws s3 sync {{ hospedate_bucket_origin }} {{ hospedate_bucket_target }}  --exact-timestamps --acl bucket-owner-full-control"
  register: s3_sync
  changed_when: false
  args:
    chdir: "/opt"

- name: "BUCKET - Output sync on file {{ hospedate_logdir }}/bucket-sync-output-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}.log"
  ansible.builtin.copy:
    content: |
      ===== STDOUT =====
      {{ s3_sync.stdout }}

      ===== STDERR =====
      {{ s3_sync.stderr }}
    dest: "{{ hospedate_logdir }}/bucket-sync-output-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}.log"
    mode: '0644'

- name: "BUCKET - Bucket history log finish sync"
  become: yes
  ansible.builtin.shell: echo "[ finish time {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}] - {{ hospedate_environment }} - BUCKET SYNC FINISH  from {{ hospedate_bucket_origin }}  to {{ hospedate_bucket_target }} " >> {{ hospedate_logdir }}/bucket-sync.log

