---

- name: "Copy from Prod  {{ hospedate_project }} - {{ hospedate_environment }} "
  block:

    - name: COPY FROM PROD - Print message if ansible version is greater than 2.7.0
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: COPY FROM PROD - Get timestamp from the system
      become_user: "{{ hospedate_user }}"
      shell: "date +%Y%m%d-%H%M"
      register: tstamp

    - name: COPY FROM PROD - Set variables
      become_user: "{{ hospedate_user }}"
      set_fact:
       my_date: "{{ tstamp.stdout[0:8]}}"
       my_time: "{{ tstamp.stdout[8:]}}"

    - name: "COPY FROM PROD - Base folder to Semaphore Server exists: {{ hospedate_local_workdir }}"
      become: yes
      ansible.builtin.file:
        path: "{{ hospedate_local_base }}"
        state: directory
        owner: "{{ hospedate_user }}"
        group: "{{ hospedate_group_security }}"
        mode: 0775
        force: yes

    - name: "COPY FROM PROD - Remote directory workdir exists: {{ hospedate_local_workdir }}/remote"
      become_user: "{{ hospedate_user }}"
      ansible.builtin.file:
        path: "{{ hospedate_local_workdir }}/remote"
        state: directory
        owner: "{{ hospedate_user }}"
        group: "{{ hospedate_group_security }}"
        mode: 0775
        force: yes

    - name: "COPY FROM PROD - log directory workdir exists: {{ hospedate_local_workdir }}/log"
      become_user: "{{ hospedate_user }}"
      ansible.builtin.file:
        path: "{{ hospedate_local_workdir }}/log"
        state: directory
        owner: "{{ hospedate_user }}"
        group: "{{ hospedate_group_security }}"
        mode: 0775
        force: yes

    - name: "COPY FROM PROD - bin directory workdir exists: {{ hospedate_local_workdir }}/bin"
      become_user: "{{ hospedate_user }}"
      ansible.builtin.file:
        path: "{{ hospedate_local_workdir }}/bin"
        state: directory
        owner: "{{ hospedate_user }}"
        group: "{{ hospedate_group_security }}"
        mode: 0775
        force: yes

    - name: COPY FROM PROD - Install - Copy the hoospedate-restore script
      become_user: "{{ hospedate_user }}"
      ansible.builtin.template:
        src: hospedate-restore.j2
        dest: "{{ hospedate_local_workdir }}/bin/hospedate-restore"
        owner: "{{ hospedate_user }}"
        group: "{{ hospedate_group_security }}"
        force: yes
        mode: 0775
      ignore_errors: yes          
        
    - name: "COPY FROM PROD - Start get backup from production"
      become_user: "{{ hospedate_user }}"
      command: >
        pg_dump  {{ hospedate_db_remote_profile }}  --host {{ hospedate_db_remote_host }}  --port {{ hospedate_db_remote_port }}  -U {{ hospedate_db_remote_username }} {{ hospedate_db_remote_exclude }}  -Fc  {{ hospedate_db_remote_name }} -f {{ hospedate_local_workdir }}/remote/{{ hospedate_db_remote_name }}-{{ my_date }}{{ my_time }}.bkp
      environment:
        PGPASSWORD: "{{ hospedate_db_remote_password }}"
      args:
        chdir: "{{ hospedate_local_workdir }}/remote"

#    - name: "COPY FROM PROD - Clean all connection"
#      become_user: "{{ hospedate_user }}"
#      ansible.builtin.shell: "export PGPASSWORD={{ hospedate_db_local_password_main }} ; psql -h {{ hospedate_db_local_host }} -p {{ hospedate_db_local_port }}  -U {{ hospedate_db_local_username_main }}  template1 -c \"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname =  '{{ hospedate_db_local_name }}' \" "

#    - name: "COPY FROM PROD - Drop database from integration"
#      become_user: "{{ hospedate_user }}"
#      ansible.builtin.shell: "export PGPASSWORD={{ hospedate_db_local_password_main }} ; psql -h {{ hospedate_db_local_host }} -p {{ hospedate_db_local_port }}  -U {{ hospedate_db_local_username_main }}  template1 -c \"DROP DATABASE  {{ hospedate_db_local_name }} \" "
      ignore_errors: yes

#    - name: "COPY FROM PROD - Create Database on integration"
#      become_user: "{{ hospedate_user }}"
#      ansible.builtin.shell: "export PGPASSWORD={{ hospedate_db_local_password_main }} ; psql -h {{ hospedate_db_local_host }} -p {{ hospedate_db_local_port }}  -U {{ hospedate_db_local_username_main }}  template1 -c \"CREATE DATABASE {{ hospedate_db_local_name }} \" "

#    - name: "COPY FROM PROD - Previus settinng  Database on integration"
#      become_user: "{{ hospedate_user }}"
#      ansible.builtin.shell: "export PGPASSWORD={{ hospedate_db_local_password_main }} ; psql -h {{ hospedate_db_local_host }} -p {{ hospedate_db_local_port }}  -U {{ hospedate_db_local_username_main }}  template1 -c \"{{ hospedate_db_previous_command }} \" "
#      ignore_errors: yes

#    - name: "COPY FROM PROD - Start RESTORING for backup"
#      become_user: "{{ hospedate_user }}"
#      command: >
#        pg_restore {{ hospedate_db_restoring_profile }}  --host {{ hospedate_db_local_host }}  --port {{ hospedate_db_local_port }} -U {{ hospedate_db_local_username_main }}  -Fc -d {{ hospedate_db_local_name }} "{{ hospedate_local_workdir }}/remote/{{ hospedate_db_remote_name }}-{{ my_date }}{{ my_time }}.bkp"
#      environment:
#        PGPASSWORD: "{{ hospedate_db_local_password_main }}"
#      ignore_errors: yes

#    - name: "COPY FROM PROD - Finish backup "
#      become_user: "{{ hospedate_user }}"
#      ansible.builtin.shell: "echo '{{ my_date }}{{ my_time }} [RESTORING] Creating restoring form backup {{ hospedate_local_workdir }}/remote/{{ hospedate_db_remote_name }}-{{ my_date }}{{ my_time}}.bkp from the database {{ hospedate_db_local_name }}' >> {{ hospedate_local_workdir }}/log/copyfromprod.log"



